import {test} from 'node:test';
import assert from 'node:assert/strict';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,id,parseUnits} from 'ethers';
import {readFileSync} from 'node:fs';
test('Fund, submit, allocate, claim and refund lifecycle',async()=>{
const rpc=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai'}});
const provider=new BrowserProvider(rpc);provider.pollingInterval=10;
const a=await provider.getSigner(0),b=await provider.getSigner(1),c=await provider.getSigner(2);
const artifact=n=>JSON.parse(readFileSync(`public/artifacts/${n}.json`));
const t=artifact('ReviewToken'),p=artifact('ReviewPool');
const token=await new ContractFactory(t.abi,t.bytecode,a).deploy();await token.waitForDeployment();
const pool=await new ContractFactory(p.abi,p.bytecode,a).deploy(await token.getAddress());await pool.waitForDeployment();
const tx=async x=>await (await x).wait();
await tx(token.faucet());const amount=parseUnits('100',6);await tx(token.approve(await pool.getAddress(),amount*2n));
const now=Number((await provider.getBlock('latest')).timestamp),deadline=now+100;
const key=id('review1');await tx(pool.fund(key,amount,deadline,id('brief')));
assert.equal(await token.balanceOf(await pool.getAddress()),amount);
await assert.rejects(tx(pool.fund(key,amount,deadline,id('brief'))));
await assert.rejects(tx(pool.submit(key,id('creator-review'))));
await tx(pool.connect(b).submit(key,id('b-review')));
await assert.rejects(tx(pool.connect(b).submit(key,id('duplicate'))));
await tx(pool.connect(c).submit(key,id('c-review')));
await assert.rejects(tx(pool.resolve(key,[await b.getAddress()],[amount])));
await rpc.request({method:'evm_increaseTime',params:[101]});await rpc.request({method:'evm_mine',params:[]});
await assert.rejects(tx(pool.connect(b).resolve(key,[await b.getAddress()],[amount])));
await assert.rejects(tx(pool.resolve(key,[await a.getAddress()],[amount])));
await assert.rejects(tx(pool.resolve(key,[await b.getAddress(),await b.getAddress()],[amount/2n,amount/2n])));
await assert.rejects(tx(pool.resolve(key,[await b.getAddress()],[amount-1n])));
await tx(pool.resolve(key,[await b.getAddress(),await c.getAddress()],[amount/2n,amount/2n]));
await tx(pool.connect(b).claim(key));assert.equal(await token.balanceOf(await b.getAddress()),amount/2n);
await assert.rejects(tx(pool.connect(b).claim(key)));
await tx(pool.connect(c).claim(key));assert.equal(await token.balanceOf(await pool.getAddress()),0n);
await assert.rejects(tx(pool.refund(key)));
const key2=id('refund');await tx(pool.fund(key2,amount,deadline+200,id('brief2')));
await assert.rejects(tx(pool.refund(key2)));
await rpc.request({method:'evm_increaseTime',params:[604801+200]});await rpc.request({method:'evm_mine',params:[]});
await assert.rejects(tx(pool.resolve(key2,[await b.getAddress()],[amount])));
await tx(pool.refund(key2,{gasLimit:150000}));assert.equal(await token.balanceOf(await pool.getAddress()),0n);
await assert.rejects(tx(pool.refund(key2)));
await rpc.disconnect();
});

test('Native ETH funding, allocation and claim',async()=>{
const rpc=ganache.provider({logging:{quiet:true}}),provider=new BrowserProvider(rpc);provider.pollingInterval=10;
const creator=await provider.getSigner(0),reviewer=await provider.getSigner(1);
const p=JSON.parse(readFileSync('public/artifacts/ReviewPool.json'));
const pool=await new ContractFactory(p.abi,p.bytecode,creator).deploy('0x0000000000000000000000000000000000000000');await pool.waitForDeployment();
const tx=async promise=>(await promise).wait();
const key=id('native'),amount=parseUnits('0.001',18),now=(await provider.getBlock('latest')).timestamp;
await assert.rejects(tx(pool.fund(key,amount,now+50,id('brief'))));
await tx(pool.fund(key,amount,now+50,id('brief'),{value:amount}));
await tx(pool.connect(reviewer).submit(key,id('review')));
await rpc.request({method:'evm_increaseTime',params:[51]});await rpc.request({method:'evm_mine',params:[]});
await tx(pool.resolve(key,[await reviewer.getAddress()],[amount]));
assert.equal(await pool.claimable(key,await reviewer.getAddress()),amount);
await tx(pool.connect(reviewer).claim(key));
assert.equal(await pool.claimable(key,await reviewer.getAddress()),0n);
assert.equal(BigInt(await rpc.request({method:'eth_getBalance',params:[await pool.getAddress(),'latest']})),0n);
await assert.rejects(tx(pool.connect(reviewer).claim(key)));
await rpc.disconnect();
});

test('Native pools remain isolated; invalid funding and late submissions revert',async()=>{
 const rpc=ganache.provider({logging:{quiet:true}}),provider=new BrowserProvider(rpc);provider.pollingInterval=10;
 try{
 const a=await provider.getSigner(0),b=await provider.getSigner(1),c=await provider.getSigner(2);
 const p=JSON.parse(readFileSync('public/artifacts/ReviewPool.json'));
 const pool=await new ContractFactory(p.abi,p.bytecode,a).deploy('0x0000000000000000000000000000000000000000');await pool.waitForDeployment();
 const tx=async promise=>(await promise).wait(),now=Number((await provider.getBlock('latest')).timestamp),amount=parseUnits('0.002',18),one=id('isolated-1'),two=id('isolated-2');
 await assert.rejects(tx(pool.fund(id('zero'),0,now+60,id('brief'))));
 await assert.rejects(tx(pool.fund(id('bad-value'),amount,now+60,id('brief'),{value:amount-1n})));
 await assert.rejects(tx(pool.fund(id('late-deadline'),amount,now+91*86400,id('brief'),{value:amount})));
 await tx(pool.fund(one,amount,now+60,id('one'),{value:amount}));
 await tx(pool.fund(two,amount,now+60,id('two'),{value:amount}));
 await tx(pool.connect(b).submit(one,id('feedback')));
 await assert.rejects(tx(pool.connect(c).claim(one)));
 await rpc.request({method:'evm_increaseTime',params:[61]});await rpc.request({method:'evm_mine',params:[]});
 await assert.rejects(tx(pool.connect(c).submit(one,id('late'))));
 await tx(pool.resolve(one,[await b.getAddress()],[amount]));
 await assert.rejects(tx(pool.resolve(one,[await b.getAddress()],[amount])));
 await tx(pool.connect(b).claim(one));
 assert.equal(BigInt(await rpc.request({method:'eth_getBalance',params:[await pool.getAddress(),'latest']})),amount);
 await rpc.request({method:'evm_increaseTime',params:[604801]});await rpc.request({method:'evm_mine',params:[]});
 await assert.rejects(tx(pool.connect(b).refund(two)));
 await assert.rejects(tx(pool.refund(one)));
 await tx(pool.refund(two));
 assert.equal(BigInt(await rpc.request({method:'eth_getBalance',params:[await pool.getAddress(),'latest']})),0n);
 }finally{await rpc.disconnect()}
});
